#!/bin/sh

[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

for command in mount umount pacman su ; do
	alias $command="sudo $command"
done; unset command

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	e="$EDITOR" \
	pac="pacman" \
	v="zathura"

alias \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
